### ISSUE TITLE
Stack analyses v2 test failure on stage - usage outliers probability

### ISSUE THREAD

**Issue by tisnik** [fabric8-analytics/fabric8-analytics-server#102]
Content of the requirements.txt:

```
click==6.7
httpie==0.9.9
parsimonious==0.7.0
pygments==2.2.0
six==1.10.0
wheel==0.30.0a0
setuptools==36.0.1
```

Stack analyses v2 response (part of it):

```
                "usage_outliers": [
...
... skipped
...
                    {
                        "outlier_prbability": 0.7802197802199999,
                        "package_name": "click"
                    }
                ]
```

According to the newest version of https://github.com/fabric8-analytics/fabric8-analytics-stack-analysis/blame/master/analytics_platform/kronos/pgm/src/pgm_constants.py#L22 the constant should be greater than 0.9

See https://github.com/fabric8-analytics/fabric8-analytics-stack-analysis/commit/774f362211c27ddd4b979538c450d2df700d5b26

**Comment by samuzzal-choudhury** [comment]
@tisnik The usage outlier calculation has been corrected ATM. Hence, closing this issue. Please reopen this if you think otherwise.
