### ISSUE TITLE
Stack Analysis Report - Latest version number is lesser than the current version

### ISSUE THREAD

**Issue by arunkumars08** [fabric8-analytics/fabric8-analytics-server#103]
<img width="1440" alt="screen shot 2017-08-01 at 2 13 24 pm" src="https://user-images.githubusercontent.com/7880465/28817188-17593ef4-76c5-11e7-88b2-8982aba77ea0.png">

**Comment by GeorgeActon** [comment]
Latest version comes from Anitya which may be out of sync. Mitesh is working on that problem so retest when his work is done.

**Comment by samuzzal-choudhury** [comment]
The current implementation of stack analysis on OSIO makes use of libraries.io for the latest version which seems to be working fine. Hence, closing this issue. @arunkumars08 please reopen if you think otherwise.
