### ISSUE TITLE
Failures on stage: HTTP code 500 Internal Server Error is returned  for the stack analysis results

### ISSUE THREAD

**Issue by tisnik** [fabric8-analytics/fabric8-analytics-server#108]
The test case with the "standard" requirements.txt sometimes fails with the 500 Internal Server Error. The probability of failure is approximately 4/10 analysis.

**Comment by samuzzal-choudhury** [comment]
This issue was moved to openshiftio/openshift.io#659

**Comment by samuzzal-choudhury** [comment]
Corresponding openshift.io issue has been addressed openshiftio/openshift.io#659. Hence, closing.
