### ISSUE TITLE
Failure on stage: empty recommendations node in the stack analysis

### ISSUE THREAD

**Issue by tisnik** [fabric8-analytics/fabric8-analytics-server#110]
The input requirements.txt file:

```
click==6.7
httpie==0.9.9
parsimonious==0.7.0
pygments==2.2.0
six==1.10.0
wheel==0.30.0a0
setuptools==36.0.1
```

In the analyzed output, the recommendations node is empty: []

**Comment by samuzzal-choudhury** [comment]
@tisnik,  The block that you observed was the partially filled in one. Recommendation task takes more time to complete and hence you observed this behaviour. A subsequent GET of /stack-analyses-v2 normally yields recommendations.

Please feel free to reopen the issue if you think otherwise.
