### ISSUE TITLE
Unknown components' count not proper stack analysis v2

### ISSUE THREAD

**Issue by arunkumars08** [fabric8-analytics/fabric8-analytics-server#131]
Tried with this stack

httpie==0.9.9
parsimonious==0.7.0
pygments==2.2.0
six==1.10.0
wheel==0.30.0a0
setuptools==36.0.1

According to the analysis only 3 components are known (Analyzed), then unknown count has to be 4. It is returned as 0.

https://gist.github.com/arunkumars08/1b00bf595b5877bee5a773a91abc5c5f

**Comment by sara-02** [comment]
Facing similar issue with the Quickstart applications as well.

![screenshot from 2017-08-24 18-31-32](https://user-images.githubusercontent.com/7047079/29709314-64c0dd78-897b-11e7-9f9a-e874dccab2dc.png)

**Comment by samuzzal-choudhury** [comment]
This issue was moved to openshiftio/openshift.io#849
