### ISSUE TITLE
Getting 500 in stack-analysis-v2 on get call after successfully getting stack ID for analysis

### ISSUE THREAD

**Issue by invincibleJai** [fabric8-analytics/fabric8-analytics-server#132]
1) uploaded single manifest file (requirements.txt) with contents : 
`click==6.7`
`httpie==0.9.9`
`parsimonious==0.7.0`
`pygments==2.2.0`
`six==1.10.0`
`wheel==0.30.0a0`
`setuptools==36.0.1`

2) got Stack ID `25ea680bdf4241e88be8490856840f72` get call works fine

3) add one more component(invalid one) to above requirements.txt
`click==6.7`
`httpie==0.9.9`
`parsimonious==0.7.0`
`pygments==2.2.0`
`six==1.10.0`
`wheel==0.30.0a0`
`setuptools==36.0.1`
`setupjai==36.0.1`

3) got stack ID `9b37c93b5ee14dea93ee31bc17b050c6` , get call gives 500 now with error message 
`{
    "error": "Invalid manifest file(s) received. Please submit valid manifest files for stack analysis"
}`

**Comment by samuzzal-choudhury** [comment]
This issue was moved to openshiftio/openshift.io#850
