### ISSUE TITLE
RFE: the API endpoint to force analysis for selected component on given ecosystem

### ISSUE THREAD

**Issue by tisnik** [fabric8-analytics/fabric8-analytics-server#139]
Currently, the following endpoint called with GET method starts analysis for selected component+version only when the analysis is not finished already:

```
/api/v1/component-analyses/<ecosystem>/<package>/<version>
```

It would be nice to have the same endpoint, but for the method POST or PUT to force new analysis, even if old analysis already exists.

**Comment by fridex** [comment]
An idea for next iteration - we could make it more "sensitive" by providing endpoint for updating only certain task results (as we already have selective task runs). A user could say - I want to update only github data and so. This would be similar to https://github.com/fabric8-analytics/fabric8-analytics-server/issues/38

**Comment by tisnik** [comment]
It would be really nice @fridex, TY in advance :)

**Comment by samuzzal-choudhury** [comment]
This issue was moved to openshiftio/openshift.io#853
