### ISSUE TITLE
RFE: add new attributes started_at and finished_at to component analysis response

### ISSUE THREAD

**Issue by tisnik** [fabric8-analytics/fabric8-analytics-server#140]
It would be nice to have ```started_at``` and ```finished_at``` attributes in the component analysis response with the same meaning, as for stack analysis. Ideally that attributes would represent UTC time in format ```%Y-%m-%dT%H:%M:%S.%f``` or ```%Y-%m-%dT%H:%M:%S``` (w/o milliseconds)

**Comment by fridex** [comment]
This is not that straightforward for us as we provide response based on data that are available in the graph AFAIK. This information is tracked in the init/finalize task and subsequently closed (finished_at) in the finalize task (or finalize task error task).

We would probably need to sync even `InitBayesianFlow` task to graph to expose such information. CC @miteshvp

**Comment by fridex** [comment]
We looked at the current output of component-analyses endpoint with @tisnik and it looks like we are not providing information about task run (when the given task was run and when finished) - parts of the `_audit` field we have for each task.

These metadata are especially helpful when providing data that change in time (e.g. github data) so a user is aware of data age (and can possibly force updates on demand). Also it will make testing and benchmarking a lot easier for @tisnik.

@samuzzal-choudhury @miteshvp Could we reintroduce these audit logs?

**Comment by samuzzal-choudhury** [comment]
This issue was moved to openshiftio/openshift.io#854
