### ISSUE TITLE
Source code style improvement: do not use bare except

### ISSUE THREAD

**Issue by tisnik** [fabric8-analytics/fabric8-analytics-server#153]
Can anybody with the knowledge about the code fix the following warnings about not-so-nice code style?

```
auth.py:160:9: E722 do not use bare except'
utils.py:89:9: E722 do not use bare except'
utils.py:106:9: E722 do not use bare except'
utils.py:238:5: E722 do not use bare except'
```

It's detected for source files from the ```bayesian``` directory. TYVM in advance

**Comment by samuzzal-choudhury** [comment]
This issue was moved to openshiftio/openshift.io#856
