### ISSUE TITLE
README.md: Link to the RAML file is invalid

### ISSUE THREAD

**Issue by tisnik** [fabric8-analytics/fabric8-analytics-server#20]
The link mentioned in the *API definition* section is invalid. It points to the non existent file:

https://github.com/fabric8-analytics/fabric8-analytics-server/blob/docs/api/raml/api.raml

**Comment by samuzzal-choudhury** [comment]
Related Issue https://github.com/openshiftio/openshift.io/issues/833 opened. Closing this to avoid duplications.
