### ISSUE TITLE
Probably wrong error message is displayed for API call /stack-analyses/_ANY_ID_

### ISSUE THREAD

**Issue by tisnik** [fabric8-analytics/fabric8-analytics-server#22]
The following API call always returned the same error message that just repeats the ID (whatever the ID is, even for empty analysis queue):

```
curl localhost:32000/api/v1/stack-analyses/ANYTHING
{
  "error": "Analysis for request ID 'ANYTHING' is in progress"
}
```

**Comment by tisnik** [comment]
The similar issue can be seen for the stack-analyses-v2 endpoint as well

**Comment by samuzzal-choudhury** [comment]
Fixed for stack-analyses-v2 as well. Closing this. Please feel free to reopen if you think otherwise.
