### ISSUE TITLE
Miss-leading API response

### ISSUE THREAD

**Issue by pkajaba** [fabric8-analytics/fabric8-analytics-server#23]
When I try to create an analysis for one component for the first time I got this response:
```
$ curl  http://localhost:32000/api/v1/component-analyses/maven/io.vertx:vertx-core/3.4.1
{
  "error": "No data found for maven Package io.vertx:vertx-core/3.4.1"
}
```
I believe it's not an error that there are no data and I think that when there is analysis in progress for this package there could be information about it instead of this "error" message.

**Comment by pkajaba** [comment]
@samuzzal-choudhury What do you think about it?

**Comment by fridex** [comment]
> I believe it's not an error that there are no data and I think that when there is analysis in progress for this package there could be information about it instead of this "error" message.

+1 for a more descriptive message.

**Comment by samuzzal-choudhury** [comment]
@pkajaba sorry for the long delay. +1.

**Comment by samuzzal-choudhury** [comment]
This issue was moved to openshiftio/openshift.io#834
