### ISSUE TITLE
RFE: Document the current API

### ISSUE THREAD

**Issue by tisnik** [fabric8-analytics/fabric8-analytics-server#26]
As API has changed a lot there's a need to document the current API so the integration tests could be created and the test coverage could be computed as well.

**Comment by fridex** [comment]
+1, I will work on proposal for v2 API as the current API is introducing challenges in many aspects.

Also there are present schemas which I believe are now not useful for API as there is a significant difference in what results are stored vs what is the actual schema when it comes to presentation on the API side

**Comment by tisnik** [comment]
Thanks @fridex. Please let me know if you want any form of help from my side.

**Comment by fridex** [comment]
@tisnik OK, I will let you know once I will start work on this. Thanks!

**Comment by samuzzal-choudhury** [comment]
This issue was moved to openshiftio/openshift.io#835
