### ISSUE TITLE
RFE: implement some sort of code quality tests (lints)

### ISSUE THREAD

**Issue by tisnik** [fabric8-analytics/fabric8-analytics-server#30]
This is part of the overall QA coverage of fabric8 project.

**Comment by fridex** [comment]
There was a plan to add some linters such as pylint or coala bears but it never happened. I think it will require quiet large effort as the current code base does not conform to pep standards, but it would increase code quality a lot (as well as PR code quality).

**Comment by samuzzal-choudhury** [comment]
This issue was moved to openshiftio/openshift.io#838
