### ISSUE TITLE
Create a Sentiment Analysis API for Che integration

### ISSUE THREAD

**Issue by SaketJNU** [fabric8-analytics/fabric8-analytics-server#32]
It is planned to integrate 'sentiment-analysis' with 'Che' similar to 'component-analysis'.  The sentiment-analysis will require the "Google Big-Query" to read data from 'stackoverflow tables'and "Google Cloud Natural Language API" to compute sentiment_details. The following attached document [1] contains the work-flow diagram, block-diagram and few others details.
[1] https://docs.google.com/a/redhat.com/document/d/15Pq9WNz2WuyP2PsIUvkUMAxCpCX13yROuM233QAag70/edit?usp=sharing

cc: @miteshvp

**Comment by samuzzal-choudhury** [comment]
Done already. Hence, closing.
