### ISSUE TITLE
Incorrect HTTP status when the job to be deleted does not exists

### ISSUE THREAD

**Issue by tisnik** [fabric8-analytics/fabric8-analytics-server#34]
curl -v -X DELETE localhost:34000/api/v1/jobs/UNKNOWN_JOB

returns HTTP code:

HTTP/1.1 401 UNAUTHORIZED

Should be either:

DELETE /api/documents/2 - 404 Users permission irrelevant, resource does not exist
DELETE /api/documents/1 - 410 User has permission, resource already deleted

**Comment by fridex** [comment]
I suppose this should go to the jobs issue tracker. Nevertheless nice catch!

**Comment by tisnik** [comment]
This issue has been moved to the correct repository: https://github.com/fabric8-analytics/fabric8-analytics-jobs/issues/68. I'm sorry for confusion.
