### ISSUE TITLE
Don't use usersys docker registry (same as fabric8-common)?

### ISSUE THREAD

**Issue by tisnik** [fabric8-analytics/fabric8-analytics-server#41]
I'm not sure here, but should not we make the change similar to:
https://github.com/fabric8-analytics/fabric8-analytics-common/commit/72e18c5dad39ab3abb6cb6db73f762fc3367de56
?

**Comment by fridex** [comment]
Related PR: https://github.com/fabric8-analytics/fabric8-analytics-server/pull/42

**Comment by samuzzal-choudhury** [comment]
@tisnik  This has been fixed already. Please reopen if you think otherwise
