### ISSUE TITLE
Do not pass manifest files via SQS queue

### ISSUE THREAD

**Issue by fridex** [fabric8-analytics/fabric8-analytics-server#43]
Currently, all manifest files are sent on queue as part of message. Note that there could be multiple manifest files and the limit of one single message is 256KB [1]. As we already pass other metadata related to task flows in the message (such as flow related metadata that are necessary for dispatcher), flow arguments and Celery related metadata so this limit can be easily reached.

Instead, we should pass only reference to S3 object stored on S3.

[1] http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/limits-messages.html

**Comment by samuzzal-choudhury** [comment]
Already fixed in the following PRs - 

Server fabric8-analytics/fabric8-analytics-server#144
Worker fabric8-analytics/fabric8-analytics-worker#293

Hence, closing.
