### ISSUE TITLE
Stack analysis wrong API response 

### ISSUE THREAD

**Issue by arunkumars08** [fabric8-analytics/fabric8-analytics-server#61]
If you request with an unknown id you get the misleading error that the analysis is in progress:

$ curl -H "Authorization: Bearer $OSIO_TOKEN" https://recommender.api.openshift.io/api/v1/stack-analyses/someunkownid
{
  "error": "Analysis for request ID 'someunkownid' is in progress"
}
This is especially misleading as it is the same message if there is a legitimate analysis in progress. But that case should not be noted as an "error".

Main reference: https://github.com/openshiftio/openshift.io/issues/276

**Comment by fridex** [comment]
Related/duplicit: https://github.com/fabric8-analytics/fabric8-analytics-server/issues/22 and https://github.com/fabric8-analytics/fabric8-analytics-server/issues/23

**Comment by samuzzal-choudhury** [comment]
This issue does not exist any more. Please feel free to reopen if you think otherwise.
