### ISSUE TITLE
RFE: support for '-r' option in the requirements.txt (PyPi ecosystem)

### ISSUE THREAD

**Issue by tisnik** [fabric8-analytics/fabric8-analytics-server#76]
According to the documentation (https://pip.pypa.io/en/latest/reference/pip_install/#requirements-file-format) and real requirements.txt files I've found:

it is possible to use the following option to refer to other requirements file:

```
-r more_requirements.txt
```

It seems that it is not supported in fabric8-analytics right now.

**Comment by samuzzal-choudhury** [comment]
This issue was moved to openshiftio/openshift.io#846
