### ISSUE TITLE
The * character in final releases does not work in stack analysis v2

### ISSUE THREAD

**Issue by tisnik** [fabric8-analytics/fabric8-analytics-server#79]
It seems that * character that is allowed to specify final releases for package
https://www.python.org/dev/peps/pep-0440/#final-releases
does not work in stack analysis v2

requirements.txt to check:

```
click==6.*
```

on the other hand this one works:

```
click==6.7.*
```

**Comment by samuzzal-choudhury** [comment]
This issue was moved to openshiftio/openshift.io#848
