### ISSUE TITLE
Multiple manifest file support across all supported ecosystems

### ISSUE THREAD

**Issue by jyasveer** [fabric8-analytics/fabric8-analytics-server#93]

**Comment by jyasveer** [comment]
https://docs.google.com/a/redhat.com/spreadsheets/d/1HMKtwRyO5SgC-CUTGWf-p45GRp3FGY99sDlB3gaUIOQ/edit?usp=sharing

**Comment by samuzzal-choudhury** [comment]
The support has already been added to prod. Hence, closing this.
